schema_version = "1.0.0"
id = "bake_one_click"
version = "1.23.0"
name = "Bake One Click"
tagline = "One-click baking with layered output to PSD"
maintainer = "yixiu"
type = "add-on"
license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "5.1.0"
tags = ["Bake", "Object", "UV", "PSD"]

platforms = [
    "windows-x64",
    "macos-arm64",
    "macos-x64",
    "linux-x64",
]

wheels = [
    "./wheels/bake_one_click_core-1.23.0-cp313-cp313-win_amd64.whl",
    "./wheels/bake_one_click_core-1.23.0-cp313-cp313-macosx_10_13_universal2.whl",
    "./wheels/bake_one_click_core-1.23.0-cp313-cp313-linux_x86_64.whl",
]